<?php
if (empty($_SESSION['quantity_product_in_cart'])) {
  $_SESSION['quantity_product_in_cart'] = 0;
}
?>
<!DOCTYPE html>
<html lang="vi">

<head>
  <title><?= $title ?></title>
  <?php require_once './app/views/client/header_tag.phtml' ?>
  <?php require_once './app/views/client/css_general.phtml' ?>
  <?php if (!empty($style_css)) : ?>
    <link rel="stylesheet" href="<?= "{$style_css}?" . time() ?>">
  <?php endif; ?>
</head>


<body>
  <div id="wrapper">
    <?php require_once './app/views/client/header.phtml' ?>
    <?php
    if (!empty($data)) {
      $this->render($main_content, $data);
    } else {
      $this->render($main_content);
    }
    ?>
    <?php require_once './app/views/client/footer.phtml' ?>
  </div>
  <?php require_once './app/views/client/footer_tag.phtml' ?>
</body>

</html>