<?php
if (empty($_SESSION['quantity_product_in_cart'])) {
  $_SESSION['quantity_product_in_cart'] = 0;
}
?>
<!DOCTYPE html>
<html lang="vi">

<head>
  <title><?= $title ?></title>
  <link rel="shortcut icon" href="./public/client/imgs/logo.png" type="image/x-icon">
  <?php $this->assign('client.header_tag') ?>
  <?php $this->assign('client.css_general') ?>
  <?php if (!empty($style_css)) : ?>
    <link rel="stylesheet" href="<?= "{$style_css}?" . time() ?>">
  <?php endif; ?>
</head>


<body>
  <div id="wrapper">
    <?php $this->assign('client.header') ?>
    <?php
    if (!empty($data)) {
      $this->assign($main_content, $data);
    } else {
      $this->assign($main_content);
    }
    ?>
    <?php $this->assign('client.footer') ?>
  </div>
  <?php $this->assign('client.footer_tag') ?>
</body>

</html>